#!/usr/bin/env python3
"""
Context provider hook - returns relevant context based on current file/query.

Triggered on specific patterns to provide proactive context.
This hook helps Claude Code understand project-specific patterns
when editing files in specific domains (audio, bluetooth, etc.).
"""

import json
import sys


def get_context_for_path(file_path: str) -> dict:
    """Return relevant context based on file being edited.

    Args:
        file_path: Path to the file being edited

    Returns:
        dict with relevant_files, patterns, and warnings
    """
    context = {"relevant_files": [], "patterns": [], "warnings": []}

    file_lower = file_path.lower()

    # Audio/PipeWire context
    if "pipewire" in file_lower or "audio" in file_lower or "wireplumber" in file_lower:
        context["relevant_files"] = [
            "modules/home-manager/audio/pipewire.nix",
            "hosts/nixos/hardware-configuration.nix"
        ]
        context["patterns"].append(
            "WirePlumber: Check bluetooth headset profile switching - "
            "disable auto switching in wireplumber.conf if needed"
        )
        context["warnings"].append(
            "Avoid modifying hardware-configuration.nix directly - "
            "it's auto-generated by nixos-generate-config"
        )

    # Bluetooth context
    if "bluetooth" in file_lower:
        context["patterns"].append(
            "Use hardware.bluetooth.settings for bluetooth config"
        )
        context["patterns"].append(
            "WirePlumber handles audio routing for bluetooth devices"
        )
        context["patterns"].append(
            "Known fix: Disable auto headset profile in WirePlumber "
            "to prevent audio issues with AirPods"
        )

    # NixOS module context
    if "modules/core" in file_lower:
        context["patterns"].append(
            "System-wide packages go in environment.systemPackages"
        )
        context["warnings"].append(
            "Changes require sudo nixos-rebuild - use ./rebuild-nixos"
        )

    # Home Manager context
    if "home-manager" in file_lower:
        context["patterns"].append(
            "User programs use programs.<name>.enable pattern"
        )
        context["patterns"].append(
            "User packages go in home.packages"
        )

    # Flake context
    if "flake.nix" in file_lower:
        context["patterns"].append(
            "All inputs should follow nixpkgs for consistency"
        )
        context["patterns"].append(
            "New inputs need to be added to outputs function parameters"
        )
        context["warnings"].append(
            "Run 'nix flake check' after modifying flake.nix"
        )

    return context


if __name__ == "__main__":
    if len(sys.argv) > 1:
        result = get_context_for_path(sys.argv[1])
        # Only output if there's relevant context
        if result["relevant_files"] or result["patterns"] or result["warnings"]:
            print(json.dumps(result, indent=2))
    else:
        # No file path provided, output empty context
        print(json.dumps({"relevant_files": [], "patterns": [], "warnings": []}))
